### ISSUE TITLE
[Bug]: Can't use decimals on crafting settings

### ISSUE THREAD

**Issue by Aftertale-Sans** [Lorenzo0111/QualityArmory#402]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Whenever I launch up the server, I get this:

[09:39:05] [Server thread/ERROR]: Error occurred while enabling QualityArmory v2.0.7 (Is it up to date?)
java.lang.NumberFormatException: For input string: "0.90"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.lang.Short.parseShort(Unknown Source) ~[?:?]
	at java.lang.Short.parseShort(Unknown Source) ~[?:?]
	at me.zombie_striker.qg.QAMain.convertIngredientsRaw(QAMain.java:1229) ~[QualityArmory.jar:?]
	at me.zombie_striker.qg.QAMain.convertIngredients(QAMain.java:1[199](https://aternos.org/log/#L199)) ~[QualityArmory.jar:?]
	at me.zombie_striker.qg.config.GunYMLLoader.loadGuns(GunYMLLoader.java:291) ~[QualityArmory.jar:?]
	at me.zombie_striker.qg.config.GunYMLLoader.loadGuns(GunYMLLoader.java:492) ~[QualityArmory.jar:?]
	at me.zombie_striker.qg.QAMain.reloadVals(QAMain.java:1174) ~[QualityArmory.jar:?]
	at me.zombie_striker.qg.QAMain.onEnable(QAMain.java:684) ~[QualityArmory.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-111]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[09:39:05] [Server thread/INFO]: [QualityArmory] Disabling QualityArmory v2.0.7

### Expected Behaviour

It shouldn't be doing what it's doing.

### Plugins

EssentialsX, QualityArmory, ProtocolLib, NBTAPI, CoreProtect, DropHeads, WorldEdit, SinglePlayerSleep

### Server Version

1.19.1

### Relevant log output

```shell
[09:39:05] [Server thread/ERROR]: Error occurred while enabling QualityArmory v2.0.7 (Is it up to date?)
java.lang.NumberFormatException: For input string: "0.90"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.lang.Short.parseShort(Unknown Source) ~[?:?]
	at java.lang.Short.parseShort(Unknown Source) ~[?:?]
	at me.zombie_striker.qg.QAMain.convertIngredientsRaw(QAMain.java:1229) ~[QualityArmory.jar:?]
	at me.zombie_striker.qg.QAMain.convertIngredients(QAMain.java:1[199](https://aternos.org/log/#L199)) ~[QualityArmory.jar:?]
	at me.zombie_striker.qg.config.GunYMLLoader.loadGuns(GunYMLLoader.java:291) ~[QualityArmory.jar:?]
	at me.zombie_striker.qg.config.GunYMLLoader.loadGuns(GunYMLLoader.java:492) ~[QualityArmory.jar:?]
	at me.zombie_striker.qg.QAMain.reloadVals(QAMain.java:1174) ~[QualityArmory.jar:?]
	at me.zombie_striker.qg.QAMain.onEnable(QAMain.java:684) ~[QualityArmory.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-111]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[09:39:05] [Server thread/INFO]: [QualityArmory] Disabling QualityArmory v2.0.7
```

**Comment by Lorenzo0111** [comment]
You can't use a decimal value in the crafting configuration
