### ISSUE TITLE
[Bug]: When the YMAL file starts with `# @format` this line is duplicated infinitely 

### ISSUE THREAD

**Issue by Foxxite** [Lorenzo0111/QualityArmory#538]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

When saving YMAL files while Prettier is active, a commend containing `@format` is being added tot he top of the file. For some reason this plugin keeps duplicating that comment infinitely in it's files. Causing the server to freeze and the yaml files to become gigabytes in size.

### Expected Behaviour

Comments to not be duplicated

### Plugins

N/A

### Server Version

Paper version git-Paper-195 (MC: 1.20.1)

**Comment by Foxxite** [comment]
With some more experimentation, the same behavior is observed when a comment is placed anywhere in the file. The content for the comment doesn't matter.

![image](https://github.com/ZombieStriker/QualityArmory/assets/15520655/48dcb8bb-e470-4c66-a629-46c824790d18)
![image](https://github.com/ZombieStriker/QualityArmory/assets/15520655/3cf08da1-ffe5-4ab8-9f7f-ac32d6d45b03)

**Comment by Lorenzo0111** [comment]
That's strange. Could you try updating paper?

**Comment by Foxxite** [comment]
The plugin doesn't work at all on the newest 1.20.2 version of paper. And for the latest 1.20.1 version, didn't make a difference.

1.20.2 error:
```
[14:31:49 WARN]: java.lang.NoSuchMethodException: no such method: net.minecraft.server.network.PlayerConnection.a(Packet)void/invokeVirtual
[14:31:49 WARN]:        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:915)
[14:31:49 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
[14:31:49 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3663)
[14:31:49 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2689)
[14:31:49 WARN]:        at QualityArmory.jar//me.zombie_striker.qg.xseries.ReflectionUtils.<clinit>(ReflectionUtils.java:240)
[14:31:49 WARN]:        at QualityArmory.jar//me.zombie_striker.qg.handlers.ParticleHandlers.initValues(ParticleHandlers.java:19)
[14:31:49 WARN]:        at QualityArmory.jar//me.zombie_striker.qg.QAMain.onEnable(QAMain.java:696)
[14:31:49 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[14:31:49 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[14:31:49 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[14:31:49 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[14:31:49 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644)
[14:31:49 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555)
[14:31:49 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627)
[14:31:49 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[14:31:49 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[14:31:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
[14:31:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[14:31:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[14:31:49 WARN]: Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.server.network.PlayerConnection.a(net.minecraft.network.protocol.Packet)'
[14:31:49 WARN]:        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[14:31:49 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
[14:31:49 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:991)
[14:31:49 WARN]:        ... 17 more
```

**Comment by Lorenzo0111** [comment]
I can't reproduce the issue. Can you send me your config.yml?

**Comment by Foxxite** [comment]
It's just the default config. But as soon as a comment is added it does that.

Runtime info:
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.9+9) Host: Linux 5.15.0-82-generic (aarch64)

```yaml
ENABLE-DEBUG: false
language: en
FriendlyFireEnabled: false
KickPlayerIfDeniedResourcepack: true
useDefaultResourcepack: false
EnableWeaponDurability: false
BulletDetection:
  step: 0.1
BlockBullets:
  door: true
  halfslabs: false
  leaves: true
  water: false
  glass: true
enableInteract:
  Chests: true
overrideAnvil: false
showPossibleCrashHelpMessage: true
anticheatFix: false
verboseItemLogging: false
enable_permssionsToShoot: false
sendOnJoin: true
sendTitleOnJoin: false
SecondsTillRPIsSent: 5.0
enableBulletTrails: true
BulletTrailsSpacing: 0.5
enableIgnoreArmorProtection: false
enableIgnoreUnbreakingChecks: false
enableIgnoreSkipForBasegameItems: false
Items:
  enable_Unbreaking: true
enableReloadingOnDrop: false
enableReloadingWhenSwapToOffhand: false
enableReloadOnlyWhenSwapToOffhand: false
allowGunHitEntities: false
showOutOfAmmoOnTitle: true
showReloadingTitle: false
showAmmoInXPBar: true
perWeaponPermission: false
enableExplosionDamage: false
enableExplosionDamageDrop: false
enablePrimaryWeaponLimiter: false
weaponlimiter_primaries: 2
weaponlimiter_secondaries: 2
enableCrafting: true
enableShop: false
AUTO-UPDATE: true
Swap-Reload-and-Shooting-Controls: false
Order-Shop-By-Price: false
enable_lore_gun-info_messages: false
enable_lore_control-help_messages: true
Enable_Headshot_Instantkill: false
Enable_Headshot_Notification_Sound: true
Headshot_Notification_Sound: entity.experience_orb.pickup
Enable_Headshot_Sounds: true
Enable_AutoArm_Grenades: false
gravityConstantForDropoffCalculations: 0.05
allowGunReload: true
Auto-Detect-Resourcepack: true
ManuallyOverrideTo_1_8_systems: false
ManuallyOverrideTo_1_13_systems: false
ManuallyOverrideTo_1_14_systems: false
unknownTranslationKeyFixer: false
Enable_Creation_Of_Default_Files: true
EnableGlowEffects: false
Break-Block-Texture-If-Shot: true
enableRecoil: true
experimental:
  BulletWounds:
    InitialBloodLevel: 1500.0
    BloodIncreasePerSecond: 0.01
    Medkit_Heal_Bloodloss_Rate: 0.05
    enableBleeding: false
disableHotbarMessages:
  OutOfAmmo: false
  Shoot: true
  Reload: false
automaticallyReloadGunWhenOutOfAmmo: true
generalModifiers:
  sway:
    Run: 1.3
    Walk: 1.5
    Ironsights: 0.8
    Sneak: 0.7
deathmessages:
  enable: false
impenetrableEntityTypes:
- ARROW
DefaultResourcepackOverride: false
IronSightsOnRightClick: true
SwapSneakToSingleFire: false
DestructableMaterials:
- OAK_LEAVES
- GLASS
- GLASS_PANE
RegenDestructableBlocksAfter: 30
overrideAttackSpeed: true
DefaultResourcepack: https://github.com/ZombieStriker/QualityArmory-Resourcepack/releases/download/latest/QualityArmory.zip
```

**Comment by Lorenzo0111** [comment]
I cannot reproduce the issue. Probably related to your editor or something on your end.
