### ISSUE TITLE
"Could not pass inventory click event to QualityArmory" [Bug]: Treats item shop like an inventory, persists on reinstall/no plugins

### ISSUE THREAD

**Issue by heywhatsyoyo** [Lorenzo0111/QualityArmory#580]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Thie plugin keeps treating /qa shop like an inventory, not like a gui shop, it doesnt charge you and lets you literally take the gui items, also this keeps happening even after reinstallling the plugin and when I have no other plugins. 

### Expected Behaviour

the shop should work lol

### Plugins

n/a (this happens with no plugins)

### Server Version

1.19.4

### Relevant log output

```shell
[23:22:34] [Server thread/ERROR]: Could not pass event InventoryClickEvent to QualityArmory v2.0.14
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2773) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1133) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1110) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3736-Spigot-e4265cc-10f8667]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
        at me.zombie_striker.qg.listener.QAListener.oninvClick(QAListener.java:256) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```

**Comment by Lorenzo0111** [comment]
What server software are you running? Please run `/version` and tell me the output

**Comment by Lorenzo0111** [comment]
Fixed with last release
