### ISSUE TITLE
[Bug]: I met some problem when I try to use ironsight

### ISSUE THREAD

**Issue by python123flask** [Lorenzo0111/QualityArmory#594]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

When I use it , I found that sometimes the ironsight would not work .

### Expected Behaviour

[QualityArmory] Task #1210992 for QualityArmory v2.0.15 generated an exception
java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at net.minecraft.world.entity.item.EntityItem.a(EntityItem.java:488) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:73) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:66) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.dropItem(CraftWorld.java:495) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.dropItem(CraftWorld.java:487) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at me.zombie_striker.qg.handlers.IronsightsHandler.aim(IronsightsHandler.java:26) ~[?:?]
        at me.zombie_striker.qg.guns.utils.GunRefillerRunnable$1.run(GunRefillerRunnable.java:143) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1257) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plugins

plugin 

### Server Version

/1.20.1

### Relevant log output

```shell
[QualityArmory] Task #1210992 for QualityArmory v2.0.15 generated an exception
java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at net.minecraft.world.entity.item.EntityItem.a(EntityItem.java:488) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:73) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:66) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.dropItem(CraftWorld.java:495) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.dropItem(CraftWorld.java:487) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at me.zombie_striker.qg.handlers.IronsightsHandler.aim(IronsightsHandler.java:26) ~[?:?]
        at me.zombie_striker.qg.guns.utils.GunRefillerRunnable$1.run(GunRefillerRunnable.java:143) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1257) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by python123flask** [comment]
I think add this will help .thanks for your early reply.
if (itemStack != null && itemStack.getType() != Material.AIR) {
    world.dropItem(itemStack);
}
