### ISSUE TITLE
[Bug]: Could not pass event InventoryClickEvent to QualityArmory v2.0.16 

### ISSUE THREAD

**Issue by ORZ39** [Lorenzo0111/QualityArmory#599]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

When i update QualityArmory, then i cant buy ammo or craft them its make this error, the guns work just in creative so plz help me

452 | [00:36:40] [Server thread/ERROR]: Could not pass event InventoryClickEvent to QualityArmory v2.0.16
453 | org.bukkit.event.EventException: null
454 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
455 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
456 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
457 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
458 | at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2763) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
459 | at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:71) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
460 | at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:14) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
461 | at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
462 | at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
463 | at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
464 | at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
465 | at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
466 | at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
467 | at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
468 | at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
469 | at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
470 | at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
471 | at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
472 | at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
473 | at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
474 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
475 | at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
476 | Caused by: java.lang.IllegalArgumentException: Cannot find field with type class com.mojang.authlib.GameProfile
477 | at me.zombie_striker.qg.handlers.ReflectionsUtil.getField(ReflectionsUtil.java:64) ~[?:?]
478 | at me.zombie_striker.qg.handlers.ReflectionsUtil.getField(ReflectionsUtil.java:63) ~[?:?]
479 | at me.zombie_striker.qg.handlers.ReflectionsUtil.getField(ReflectionsUtil.java:63) ~[?:?]
480 | at me.zombie_striker.qg.handlers.ReflectionsUtil.getField(ReflectionsUtil.java:21) ~[?:?]
481 | at me.zombie_striker.qg.handlers.SkullHandler.getURL64(SkullHandler.java:99) ~[?:?]
482 | at me.zombie_striker.customitemmanager.MaterialStorage.getMS(MaterialStorage.java:95) ~[?:?]
483 | at me.zombie_striker.qg.api.QualityArmory.isAmmo(QualityArmory.java:382) ~[?:?]
484 | at me.zombie_striker.qg.api.QualityArmory.addAmmoToInventory(QualityArmory.java:672) ~[?:?]
485 | at me.zombie_striker.qg.listener.QAListener.oninvClick(QAListener.java:328) ~[?:?]
486 | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
487 | at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
488 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
489 | ... 21 more

### Expected Behaviour

it must buy or craft ammo 

### Plugins

 AdvancedRegionMarket   advancedregionmarket-3.5.3.jar  AdvancedReplay   AutoMiner   AutoMiner-v2.0.jar  BedrockPlayerManager   BedrockPlayerManager-1.4.jar  BetterChairs   BetterChairs-v1.12.0.jar  bStats   ChestShop   ChestShop.jar  ChestSort   ChestSort-14.1.0.jar  CustomEnderChest   CustomEnderChest-v1.13.1.jar  Economobs   Economobs-2.2.1.jar  EconomyShopGUI   EconomyShopGUI-6.9.1.jar  Essentials   EssentialsX-2.20.1.jar  floodgate   floodgate-spigot.jar  Geyser-Spigot   Geyser-Spigot.jar  GeyserSkinManager   GeyserSkinManager-Spigot.jar  HavenBags   LuckPerms   LuckPerms-bukkit-5.4.146.jar  LWC   LWC-2.4.0.jar  PickMeUp   pickmeup-1.3.12.jar  PlayerBags   PlayerBags-v0.2.jar  playercarry.jar  PluginMetrics   QualityArmory   QualityArmory.jar  RampenDrills   RampenDrills.jar  update   Updater   Vault   Vault.jar  ViaVersion   ViaVersion-5.1.2-SNAPSHOT.jar  WorldEdit   worldedit-bukkit-7.3.8.jar  WorldGuard   worldguard-bukkit-7.0.12-dist.jar

### Server Version

1.21.1 Spigot

### Relevant log output

```shell
[00:36:06] [Server thread/INFO]: DrSha3fot issued server command: /qa shop
[00:36:40] [Server thread/ERROR]: Could not pass event InventoryClickEvent to QualityArmory v2.0.16
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2763) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:71) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:14) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot find field with type class com.mojang.authlib.GameProfile
	at me.zombie_striker.qg.handlers.ReflectionsUtil.getField(ReflectionsUtil.java:64) ~[?:?]
	at me.zombie_striker.qg.handlers.ReflectionsUtil.getField(ReflectionsUtil.java:63) ~[?:?]
	at me.zombie_striker.qg.handlers.ReflectionsUtil.getField(ReflectionsUtil.java:63) ~[?:?]
	at me.zombie_striker.qg.handlers.ReflectionsUtil.getField(ReflectionsUtil.java:21) ~[?:?]
	at me.zombie_striker.qg.handlers.SkullHandler.getURL64(SkullHandler.java:99) ~[?:?]
	at me.zombie_striker.customitemmanager.MaterialStorage.getMS(MaterialStorage.java:95) ~[?:?]
	at me.zombie_striker.qg.api.QualityArmory.isAmmo(QualityArmory.java:382) ~[?:?]
	at me.zombie_striker.qg.api.QualityArmory.addAmmoToInventory(QualityArmory.java:672) ~[?:?]
	at me.zombie_striker.qg.listener.QAListener.oninvClick(QAListener.java:328) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
	... 21 more
```

**Comment by Lorenzo0111** [comment]
Could you provide the config of the ammo you are trying to buy?

**Comment by ORZ39** [comment]
https://github.com/user-attachments/assets/a47b91d2-49f9-46f1-a737-a522023bc571

look at my video

**Comment by Lorenzo0111** [comment]
This has been fixed in the last dev build
